// User action
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const BUSINESS_DOWNLOADED = 'BUSINESS_DOWNLOADED';
export const DOWNLOADING_BUSINESS = 'DOWNLOADING_BUSINESS';
export const CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD';
export const EDIT_FILE = 'EDIT_FILE';
export const MODELE_DOWNLOADED = 'MODELE_DOWNLOADED';
export const DOWNLOADING_MODELE = 'DOWNLOADING_MODELE';
export const CANCEL_DOWNLOAD_MODELE = 'CANCEL_DOWNLOAD_MODELE';
export const REMOVE_EDIT_FILE = 'REMOVE_EDIT_FILE';
export const UPLOADING_FILE = 'UPLOADING_FILE';
export const MULTI_UPLOAD = 'MULTI_UPLOAD';
export const UPDATE_PREPARE = 'UPDATE_PREPARE';
export const REMOVE_EDIT_PREPARE = 'REMOVE_EDIT_PREPARE';
export const CANCEL_UPLOAD = 'CANCEL_UPLOAD';
export const CANCEL_DOWNLOAD_FILE = 'CANCEL_DOWNLOAD_FILE';
export const FILE_DOWNLOADED = 'FILE_DOWNLOADED';
export const DOWNLOADING_FILE = 'DOWNLOADING_FILE';
export const UP_FOR_DOWNLOAD = 'UP_FOR_DOWNLOAD';

// News actions
export const SET_NEWS = 'SET_NEWS';
export const REFRESH_NEWS = 'REFRESH_NEWS';

// Network actions
export const UPDATE_NET_STATUS = 'UPDATE_NET_STATUS';
export const SET_INTERVAL = 'SET_INTERVAL';

// Business actions
export const SET_DOCS = 'SET_DOCS';
export const ADD_DOC = 'ADD_DOC';
export const UPDATE_DOC = 'UPDATE_DOC';
export const SET_MODELES = 'SET_MODELES';
export const SET_BUSINESS = 'SET_BUSINESS';
export const ADD_NEW_DOC = 'ADD_NEW_DOC';
export const REMOVED_NEW_DOC = 'REMOVED_NEW_DOC';
export const SET_ARBO = 'SET_ARBO';
export const SET_DOCS_TO_DOWNLOAD = 'SET_DOCS_TO_DOWNLOAD';
