export default {
  docField: [
    'localPath',
    'prepared',
    'preparedOn',
    'pageNumber',
    'reviewedOn',
    'preparedBy',
    'revisable',
    'size',
    'createdBy',
    'dossier2',
    'upLoadedOn',
    'fileName',
    'createdOn',
    'dossier1',
    'id',
    'updatedOn',
    'updatedBy',
    'commentaire',
    'dossier3',
    'serverPath',
    'reviewedBy',
    'extension',
    'reviewed',
    'locked',
    'upLoadedBy'
  ]
}