export default {
  docField: [
    'LocalPath',
    'Prepared',
    'PreparedOn',
    'PageNumber',
    'ReviewedOn',
    'PreparedBy',
    'Revisable',
    'Size',
    'CreatedBy',
    'Dossier2',
    'UpLoadedOn',
    'FileName',
    'CreatedOn',
    'Dossier1',
    'ID',
    'UpdatedOn',
    'UpdatedBy',
    'Commentaire',
    'Dossier3',
    'ServerPath',
    'ReviewedBy',
    'Extension',
    'Reviewed',
    'Locked',
    'UpLoadedBy'
  ]
}