export default {
  t_news: 't_Informations',
  t_team: 't_Equipe',
  t_teamRights: 't_TeamCorres',
  t_docs: 't_Documents',
  t_modeles: 't_Modeles',
  t_users: 't_Utilisateurs',
  t_business: 'v_AffairesVisiblesDepuisAndroid',
  t_affaires: 't_Affaires',
  docField: [
    'LocalPath',
    'Prepared',
    'PreparedOn',
    'PageNumber',
    'ReviewedOn',
    'PreparedBy',
    'Revisable',
    'Size',
    'CreatedBy',
    'Dossier2',
    'UpLoadedOn',
    'FileName',
    'CreatedOn',
    'Dossier1',
    'ID',
    'UpdatedOn',
    'UpdatedBy',
    'Commentaire',
    'Dossier3',
    'ServerPath',
    'ReviewedBy',
    'Extension',
    'Reviewed',
    'Locked',
    'UpLoadedBy'
  ]
}